version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: "monthly"
    assignees:
      - AmmarAbouZor
    commit-message:
      prefix: 'Chore: '

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: "monthly" 
    assignees:
      - AmmarAbouZor
    commit-message:
      prefix: 'Chore: '
