[package]
name = "tui-journal"
version = "0.2.0"
edition = "2021"
authors = ["Ammar Abou Zor"]
license = "MIT"
description = "Tui app allows writing and managing journals/notes from within the terminal With different local back-ends"
repository = "https://github.com/ammarabouzor/tui-journal"
readme = "README.md"
categories = ["command-line-utilities"]
keywords = ["tui", "terminal-app", "journal", "cli", "ui"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
tokio = { version = "1.29.1", features = ["full"] }
serde = { version = "1.0.166", features = ["derive"]}
serde_json = "1.0.97"
log = "0.4.17"
chrono = { version = "0.4.24", features = ["serde"] }
async-trait = "0.1.69"
clap = { version = "4.3.10", features = ["derive"] }
crossterm = {version =  "0.25", features = ["event-stream"]}
directories = "5.0.0"
simplelog = "0.12.1"
textwrap = "0.16.0"
thiserror = "1.0.40"
toml = "0.7.6"
sqlx = {version = "0.7.0", features = ["runtime-tokio-native-tls", "sqlite", "chrono"], optional = true}
futures-util = { version = "0.3", default-features = false }

# TODO: follow issue link: https://github.com/rhysd/tui-textarea/issues/19 and reapplay the migration
tui = "0.19"
tui-textarea = "0.2"
scopeguard = "1.1.0"
git2 = { version = "0.17.2", default-features = false }
rayon = "1.7.0"
# Textarea crate supports ratatui but it doesn't provide a new version on crates.io to support it
# crossterm = "0.26"
# tui = { version = "0.20", package = "ratatui" }
# tui-textarea = { git = "https://github.com/rhysd/tui-textarea", version = "0.2", features = ["ratatui-crossterm"], default-features=false}

[features]
default = ["json", "sqlite"]
json =[]
sqlite = ["dep:sqlx"]

[[bin]]
name = "tjournal"
path = "src/main.rs"

[lib]
name = "backend"
path = "backend/src/lib.rs"

[[test]]
name = "backend"
path = "backend/tests/backend.rs"
