[package]
name = "tui-journal"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "Journal Tui app. It has to back-ends to saves the data: plain text in json format and database using sqlite"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
backend = {path = "./backend/", default_features = false}

anyhow.workspace = true
async-trait.workspace = true
chrono.workspace = true
clap = { version = "4.2.4", features = ["derive"] }
crossterm = "0.25"
directories = "5.0.0"
log.workspace = true
serde.workspace = true
serde_json.workspace = true
simplelog = "0.12.1"
textwrap = "0.16.0"
thiserror = "1.0.40"
tokio = {workspace = true}
toml = "0.7.3"
tui = "0.19.0"
tui-textarea = "0.2.0"

[features]
default = ["json", "sqlite"]
json =["backend/json"]
sqlite = ["backend/sqlite"]

[workspace]
members = [
  "backend"
]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Ammar Abou Zor"]

[workspace.dependencies]
anyhow = "1.0.70"
tokio = { version = "1.28.0", features = ["full"] }
serde = { version = "1.0.158", features = ["derive"]}
serde_json = "1.0.95"
log = "0.4.17"
chrono = { version = "0.4.24", features = ["serde"] }
async-trait = "0.1.68"

[[bin]]
name = "tjournal"
path = "src/main.rs"

[[test]]
name = "backend"
path = "backend/tests/backend.rs"
