[package]
name = "tui-journal"
version = "0.3.2"
edition = "2021"
authors = ["Ammar Abou Zor"]
license = "MIT"
description = "Tui app allows writing and managing journals/notes from within the terminal With different local back-ends"
repository = "https://github.com/ammarabouzor/tui-journal"
readme = "README.md"
categories = ["command-line-utilities"]
keywords = ["tui", "terminal-app", "journal", "cli", "ui"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
tokio = { version = "1.32.0", features = ["full"] }
serde = { version = "1.0.188", features = ["derive"]}
serde_json = "1.0.107"
log = "0.4.20"
chrono = { version = "0.4.31", features = ["serde"] }
async-trait = "0.1.73"
clap = { version = "4.4.6", features = ["derive"] }
crossterm = {version =  "0.27.0", features = ["event-stream"]}
directories = "5.0.0"
simplelog = "0.12.1"
textwrap = "0.16.0"
thiserror = "1.0.49"
toml = "0.8.2"
sqlx = {version = "0.7.2", features = ["runtime-tokio-native-tls", "sqlite", "chrono"], optional = true}
futures-util = { version = "0.3", default-features = false }

scopeguard = "1.2.0"
git2 = { version = "0.18.1", default-features = false }
rayon = "1.8.0"
fuzzy-matcher = "0.3.7"
path-absolutize = "3.1.1"
tui-textarea = { version = "0.2.2", features = ["ratatui-crossterm"], default-features=false}
ratatui = { version = "0.23.0", features = ["all-widgets"]}

[features]
default = ["json", "sqlite"]
json =[]
sqlite = ["dep:sqlx"]

[[bin]]
name = "tjournal"
path = "src/main.rs"

[lib]
name = "backend"
path = "backend/src/lib.rs"

[[test]]
name = "backend"
path = "backend/tests/backend.rs"
