name: comment-changes

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  aeruginous:
    name: aeruginous
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - uses: fregante/setup-git-user@v2.0.1

      - run: |
          rustup update
          cargo install aeruginous
          aeruginous comment-changes -d ::= -o changelog.d/ -k -n 1
          git add changelog.d/
          git commit -m '[Aeruginous] Create CHANGELOG Fragment'

      - uses: peter-evans/create-pull-request@v5.0.1
        with:
          assignees: |
            AmmarAbouZor
          branch: documentation/aeruginous-comment-changes
          branch-suffix: timestamp
          labels: |
            documentation
          title: '[Aeruginous] Create CHANGELOG Fragment'
